### ISSUE TITLE
npm ERR! 404 Not Found: vue-cmap@latest

### ISSUE THREAD

**Issue by aimeefe** [doodlewind/vue-cmap#1]
npm ERR! 404 Not Found: vue-cmap@latest

**Comment by doodlewind** [comment]
`v0.0.4` is released for now.

However since this library was developed in my junior career, some of its essential points are missing, e.g. build process and `dist` files. If you want to try `leaflet` for map, I'd recommend inline this package into your `lib` path, bug reports are stilling welcomed.

Thanks again for trying!
